# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./internal/numscript/numscript.go
    goos:
      - wasip1
    goarch:
      - wasm
    tool: "tinygo"
    hooks:
      pre:
        - mkdir -p {{ dir .Path }}
    binary: ../numscript
    ldflags:
      - -X main.Version=v{{ .Version }}

checksum:
  name_template: "numscript_checksums.txt"

archives:
  - format: binary
    name_template: "numscript"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
