name: Nix CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        run: |
          nix-shell --run "go mod download"
          nix-shell --run "go mod tidy"

      - name: Build
        run: |
          mkdir -p build
          nix-shell --run "tinygo build -o build/numscript.wasm -target wasm -no-debug ./"

      - name: Test
        run: |
          nix-shell --run "go test ./..."

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: numscript-wasm
          path: build/numscript.wasm