name: NumScript WASM Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-numscript-wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Fixed version to 1.21 to be compatible with TinyGo

      - name: Run Tests
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage.txt
          verbose: true