name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/cache@v3
        with:
          path: /tmp/.cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      
      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.30.0/tinygo_0.30.0_amd64.deb
          sudo dpkg -i tinygo_0.30.0_amd64.deb

      - name: Get dependencies
        run: |
          go mod download
          go mod verify
      
      - name: Build WASM
        run: |
          mkdir -p build
          tinygo build -o build/numscript.wasm -target wasm -no-debug ./ 
          # Added -no-debug to reduce binary size
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload WASM artifact
        run: |
          gh release upload ${{ github.event.release.tag_name }} build/numscript.wasm --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}